spring:
  #Spring Boot 2.4以后对application.yml进行了彻底更新，旨在简化和合理化加载外部配置的方式。
  #需要使用旧的配置方式可以配置spring.config.use-legacy-processing = true
  #https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
  config:
    use-legacy-processing: true
  #旧的配置方式
  profiles:
    active: dev
  #新的配置方式
#    activate:
#      on-profile:
#        - dev

  # 配置文件上传限制
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件的大小
      max-request-size: 512MB # 单次请求的文件的总大小

  #logging:
  #日志存储地址
  #file: "logs/config/demo-xx.log"

#更换默认的8080端口
server:
  #端口号
  port: 8081
  #项目名，如果不设定，默认是 /
  #context-path: /demo

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.soft.mydemo.bean #配置实体类

logging:
  level:
    com.soft.mydemo: debug
  #path: /Users/jackie/workspace/rome/
  #file: springbootdemo.log

page helper:
  helperDialect: mysql
  reasonable: false  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
