# 上传的目标文件夹
upload:
  localPath: ./home/upload/localPath
  # 博客文件存放路径
  # 服务器环境
  blog: /usr/local/uploadFile/blogImg/

  # 通用上传路径，必须是全路径
  common: /usr/local/uploadFile/common/

  # 用户文件存放路径
  # 服务器环境
  userFilePath: /usr/local/uploadFile/userFile/
