spring:
  datasource:
    name: vueBlog  #数据库别名
    url: jdbc:mysql://localhost:3306/vueBlog #url 本地环境
    username: root  #用户名
    password: root1234  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

#    url: jdbc:sqlite:/Users/king/project/myDemo/BlogDatabase.db # 创建的sqlite数据库所在路径
#    username: # 因为没有用户名和密码，所以这两个参数就没有值
#    password:
#    driver-class-name: org.sqlite.JDBC # sqlite驱动

  # 配置文件上传限制
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件的大小
      max-request-size: 512MB # 单次请求的文件的总大小

  #logging:
  #日志存储地址
  #file: "logs/config/demo-xx.log"

#更换默认的8080端口
server:
  #端口号
  port: 8081
  #项目名，如果不设定，默认是 /
  #context-path: /demo

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.soft.mydemo.bean #配置实体类

logging:
  level:
    com.soft.mydemo: debug
  #path: /Users/jackie/workspace/rome/
  #file: springbootdemo.log

# 上传的目标文件夹
upload:
  localPath: ./home/upload/localPath
  # 博客文件存放路径
  # mac环境
  # blog: /Users/king/home/uploadFile/blogImg/
  # win环境
  #blog: D:\Users\king\home\uploadFile\blogImg\
  # 服务器环境
  blog: /usr/local/uploadFile/blogImg/
  # 通用上传路径，必须是全路径
  common: /Users/king/home/uploadFile/common/

  # 用户文件存放路径
  # mac环境
  #userFilePath: /Users/king/home/uploadFile/userFile/
  # win环境
  #userFilePath: D:\Users\king\home\uploadFile\userFile\
  # 服务器环境
  userFilePath: /usr/local/uploadFile/userFile/

pagehelper:
  helperDialect: mysql
  reasonable: false  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
